ingress:
  - hostname: bot-api.nomercy.tv
    service: http://api:5000
  - hostname: bot-dev-api.nomercy.tv
    service: http://api:5000
  - hostname: bot.nomercy.tv
    service: http://web:80
  - hostname: bot-dev.nomercy.tv
    service: http://web:80
  - service: http_status:404
